//------------------------------------------------------------------------------
// <auto-generated>
//    此代码是根据模板生成的。
//
//    手动更改此文件可能会导致应用程序中发生异常行为。
//    如果重新生成代码，则将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace MODEL
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class OuOAEntities : DbContext
    {
        public OuOAEntities()
            : base("name=OuOAEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public DbSet<Bill_Leave> Bill_Leave { get; set; }
        public DbSet<Ou_Department> Ou_Department { get; set; }
        public DbSet<Ou_Permission> Ou_Permission { get; set; }
        public DbSet<Ou_Role> Ou_Role { get; set; }
        public DbSet<Ou_RolePermission> Ou_RolePermission { get; set; }
        public DbSet<Ou_UserInfo> Ou_UserInfo { get; set; }
        public DbSet<Ou_UserRole> Ou_UserRole { get; set; }
        public DbSet<Ou_UserVipPermission> Ou_UserVipPermission { get; set; }
        public DbSet<WF_AutoTransactNode> WF_AutoTransactNode { get; set; }
        public DbSet<WF_BillFlowNode> WF_BillFlowNode { get; set; }
        public DbSet<WF_BillFlowNodeRemark> WF_BillFlowNodeRemark { get; set; }
        public DbSet<WF_BillState> WF_BillState { get; set; }
        public DbSet<WF_Node> WF_Node { get; set; }
        public DbSet<WF_NodeState> WF_NodeState { get; set; }
        public DbSet<WF_WorkFlow> WF_WorkFlow { get; set; }
        public DbSet<WF_WorkFlowNode> WF_WorkFlowNode { get; set; }
    }
}
